spring:
  h2:
    console:
      enabled: true
      path: '/h2-database-console'
  datasource:
    url: 'jdbc:h2:file:./data/scheduler-h2-db'
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'