spring:
  main.banner-mode: off
  jpa.hibernate.ddl-auto: validate

# jwt
# time in milisec (hour x 24 x 30 => month)
jwt:
  expirationTime: 2592000000
  secret: 'kjnfi987832jklnf@!!ds)'
  tokenHeader: 'Authorization'
  tokenPrefix: 'Bearer '


# swagger
springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
  show-actuator: true
#  group-configs:
#  - group: group_name
#    paths-to-match: /group_path/**
#  - group: group_name
#    paths-to-match: /group_path/**