services:
  scheduler_db:
    container_name: scheduler_postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password123
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432
  pg_admin:
    container_name: scheduler_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@mail.com
      PGADMIN_DEFAULT_PASSWORD: password123
    volumes:
      - type: bind
        source: ./servers.json
        target: /pgadmin4/servers.json
        read_only: true
      - type: volume
        source: pg_admin
        target: /var/lib/pgadmin
    ports:
      - 8081:80
volumes:
  database:
  pg_admin:
