name: Scheduler CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      scheduler_db:
        image: postgres:latest
        env:
          POSTGRES_DB: scheduler_db
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: password123
        ports:
          - 5432:5432
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15-ea'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Tests
        run: ./gradlew test
      - name: Build with Gradle
        run: ./gradlew build -x test
